/**
 * Controlled X Layer TESTNET merchant product: Social Media Guru.
 *
 * Synthetic aggregated social-media intelligence for marketing Objectives.
 * Real x402 payment lifecycle on eip155:1952; content is NEVER live platform
 * data. Distinct from founder_narrative_pulse (qualitative founder messaging)
 * and from Newsliquid (live Mainnet social search).
 */

import type { ExternalResourceEvidence, ExternalResourceResult } from "../providers/types";
import type { MarketOffering } from "../market/discovery";
import { validatedRequestedPurposeKind, type ResourceNeed } from "../objective/resourceNeed";
import type { ExecutionIntent } from "../management/types";
import { EXTERNAL_SOCIAL_INTELLIGENCE_PURPOSE_KIND } from "../workforce/catalog";

export const SOCIAL_MEDIA_GURU_PROVIDER_ID = "somebody_testnet_social" as const;
export const SOCIAL_MEDIA_GURU_SERVICE_ID = "social_media_guru" as const;
export const SOCIAL_MEDIA_GURU_PRODUCT_ID = "social_media_guru" as const;
export const SOCIAL_MEDIA_GURU_OFFERING_ID =
  "somebody_testnet_social:social_media_guru" as const;
export const SOCIAL_MEDIA_GURU_RESOURCE_CLASS = "proprietary_data" as const;
export const SOCIAL_MEDIA_GURU_PROVENANCE = "synthetic_test_provider" as const;
export const SOCIAL_MEDIA_GURU_NETWORK = "eip155:1952" as const;

export const SOCIAL_MEDIA_GURU_SUPPORTED_PURPOSE_KIND =
  EXTERNAL_SOCIAL_INTELLIGENCE_PURPOSE_KIND;

export type SocialMediaGuruSupportedPurposeKind =
  typeof SOCIAL_MEDIA_GURU_SUPPORTED_PURPOSE_KIND;

export const SOCIAL_MEDIA_GURU_FULFILLMENT_SCOPE = {
  serviceId: SOCIAL_MEDIA_GURU_SERVICE_ID,
  resourceClasses: [SOCIAL_MEDIA_GURU_RESOURCE_CLASS] as const,
  purposeKinds: [SOCIAL_MEDIA_GURU_SUPPORTED_PURPOSE_KIND] as const,
} as const;

export const SOCIAL_MEDIA_GURU_PURPOSE_MAX_LENGTH = 500;
export function normalizeSocialMediaGuruPurpose(
  purpose: string | null | undefined,
): string {
  return (purpose ?? "").trim().slice(0, SOCIAL_MEDIA_GURU_PURPOSE_MAX_LENGTH).trim();
}

export const SOCIAL_MEDIA_GURU_LIMITATION =
  "Synthetic Testnet social-intelligence dataset. Generated by a controlled Somebody test provider. No live TikTok / Instagram / Facebook / X data was queried. NOT NewsLiquid, NOT live platform firehose, NOT causal attribution or conversion measurement.";

/** Useful synthetic aggregates for a multi-platform social marketing Objective. */
export const SOCIAL_MEDIA_GURU_DATASET = {
  platforms: ["TikTok", "Instagram", "Facebook", "X"] as const,
  audienceBehavior: [
    "Short-form vertical video with a concrete founder pain in the first 2 seconds retains attention better than brand intros.",
    "Carousel posts that contrast \"tool\" vs \"accountable system\" language drive saves among solo operators.",
    "Comment threads reward specific workflow examples over abstract AI claims.",
  ] as const,
  trendingFormats: [
    "Before/after desk-day montages under 25 seconds (TikTok, Reels).",
    "Myth-busting text overlays on static founder photos (Instagram, Facebook).",
    "Thread-style numbered pain → fix sequences (X).",
  ] as const,
  engagementTendencies: [
    "Questions that invite \"what are you drowning in this week?\" outperform generic CTAs.",
    "Proof-of-finished-work clips outperform feature lists for click-through to landing pages.",
  ] as const,
  messagingThemes: [
    "One accountable system that notices gaps, acquires what's missing, and returns finished work.",
    "Avoid \"another dashboard\" framing; prefer outcome and ownership language.",
  ] as const,
  channelDifferences: [
    "TikTok: hook with pain in under 2s; Instagram: carousel clarity; Facebook: community Q&A; X: concise numbered threads.",
  ] as const,
  demographicStyleAggregates: [
    "Synthetic cohort skews toward solo operators and early micro-SaaS founders (not a live census).",
  ] as const,
  contentRecommendations: [
    "Lead Creative A with a specific founder pain and end on accountable delivery.",
    "Publish one platform-native cut per channel rather than identical cross-posts.",
  ] as const,
} as const;

export type SocialMediaGuruMerchantProductRequest = {
  resourceClass: string | null;
  productId: string | null;
  serviceId: string | null;
  offeringId: string | null;
  purpose: string | null;
  purposeKind: string | null;
  requestId: string | null;
};

export type SocialMediaGuruProtectedSuccessResult = {
  ok: true;
  productId: typeof SOCIAL_MEDIA_GURU_PRODUCT_ID;
  resourceClass: typeof SOCIAL_MEDIA_GURU_RESOURCE_CLASS;
  provenance: typeof SOCIAL_MEDIA_GURU_PROVENANCE;
  limitation: typeof SOCIAL_MEDIA_GURU_LIMITATION;
  purposeKind: SocialMediaGuruSupportedPurposeKind;
  purpose: string;
  requestId: string | null;
  offeringId: string | null;
  serviceId: typeof SOCIAL_MEDIA_GURU_SERVICE_ID;
  providerId: typeof SOCIAL_MEDIA_GURU_PROVIDER_ID;
  evidence: Array<{ label: string; text: string; observedAt: number }>;
  payload: {
    platforms: string[];
    audienceBehavior: string[];
    trendingFormats: string[];
    engagementTendencies: string[];
    messagingThemes: string[];
    channelDifferences: string[];
    demographicStyleAggregates: string[];
    contentRecommendations: string[];
  };
  content: string;
};

export type SocialMediaGuruProtectedErrorCode =
  | "unsupported_product_scope"
  | "incomplete_product_request"
  | "payment_required";

export type SocialMediaGuruProtectedErrorResult = {
  ok: false;
  error: SocialMediaGuruProtectedErrorCode;
  detail: string;
};

export type SocialMediaGuruProtectedResult =
  | SocialMediaGuruProtectedSuccessResult
  | SocialMediaGuruProtectedErrorResult;

const OUT_OF_SCOPE_CLAIM_PHRASES: readonly string[] = [
  "conversion rate",
  "conversion uplift",
  "a/b test",
  "causal",
  "attribution",
  "statistically significant",
  "p-value",
  "live twitter",
  "twitter firehose",
  "newsliquid",
  "actually scraped",
  "live tiktok api",
  "live instagram api",
  "customer analytics",
  "revenue forecast",
  "price of bitcoin",
  "financial market",
  "stock price",
  "wallet risk",
  "onchain risk",
];

const NEGATION_CUE =
  /(?:\b(?:not|no|nor|never|without|cannot|can'?t|avoid\w*|exclude\w*|disclaim\w*|refrain\w*|lack\w*)\b|free of)/;

export function affirmativelyClaimsOutOfScopePhrase(
  loweredPurpose: string,
): string | null {
  for (const phrase of OUT_OF_SCOPE_CLAIM_PHRASES) {
    let searchFrom = 0;
    for (;;) {
      const at = loweredPurpose.indexOf(phrase, searchFrom);
      if (at === -1) break;
      searchFrom = at + phrase.length;
      let clauseStart = 0;
      for (const separator of [".", ";", "!", "?", "\n", ",", "—"]) {
        const idx = loweredPurpose.lastIndexOf(separator, at - 1);
        if (idx + 1 > clauseStart) clauseStart = idx + 1;
      }
      const clause = loweredPurpose.slice(clauseStart, at);
      if (NEGATION_CUE.test(clause)) continue;
      return phrase;
    }
  }
  return null;
}

export function resolveSupportedPurposeKind(
  request: SocialMediaGuruMerchantProductRequest,
):
  | { ok: true; purposeKind: SocialMediaGuruSupportedPurposeKind; purpose: string }
  | { ok: false; error: SocialMediaGuruProtectedErrorCode; detail: string } {
  const purpose = normalizeSocialMediaGuruPurpose(request.purpose);
  if (!purpose) {
    return {
      ok: false,
      error: "incomplete_product_request",
      detail:
        "social_media_guru requires a bounded purpose describing the social-intelligence research question",
    };
  }
  const explicitKind = request.purposeKind?.trim() ?? "";
  if (explicitKind && explicitKind !== SOCIAL_MEDIA_GURU_SUPPORTED_PURPOSE_KIND) {
    return {
      ok: false,
      error: "unsupported_product_scope",
      detail: `purposeKind ${explicitKind.slice(0, 120)} is outside external_social_intelligence scope`,
    };
  }
  const claim = affirmativelyClaimsOutOfScopePhrase(purpose.toLowerCase());
  if (claim) {
    return {
      ok: false,
      error: "unsupported_product_scope",
      detail: `requested purpose requires ${claim}, which social_media_guru does not sell`,
    };
  }
  if (!explicitKind) {
    return {
      ok: false,
      error: "incomplete_product_request",
      detail:
        "social_media_guru requires a structured purposeKind; free-text purpose is descriptive context, not scope authority",
    };
  }
  return {
    ok: true,
    purposeKind: SOCIAL_MEDIA_GURU_SUPPORTED_PURPOSE_KIND,
    purpose,
  };
}

export function evaluateSocialMediaGuruProductFulfillment(
  request: SocialMediaGuruMerchantProductRequest,
): SocialMediaGuruProtectedResult {
  const resourceClass = request.resourceClass?.trim() ?? "";
  const serviceId = request.serviceId?.trim() ?? "";
  const productId = request.productId?.trim() ?? "";
  if (
    resourceClass &&
    resourceClass !== SOCIAL_MEDIA_GURU_RESOURCE_CLASS
  ) {
    return {
      ok: false,
      error: "unsupported_product_scope",
      detail: `resourceClass ${resourceClass} is not proprietary_data`,
    };
  }
  if (
    serviceId &&
    serviceId !== SOCIAL_MEDIA_GURU_SERVICE_ID &&
    productId !== SOCIAL_MEDIA_GURU_PRODUCT_ID
  ) {
    return {
      ok: false,
      error: "unsupported_product_scope",
      detail: `service ${serviceId || productId} is not social_media_guru`,
    };
  }
  if (
    request.offeringId &&
    request.offeringId.trim() !== SOCIAL_MEDIA_GURU_OFFERING_ID
  ) {
    return {
      ok: false,
      error: "unsupported_product_scope",
      detail: `offeringId ${request.offeringId.trim()} is not ${SOCIAL_MEDIA_GURU_OFFERING_ID}`,
    };
  }
  const resolved = resolveSupportedPurposeKind(request);
  if (!resolved.ok) return resolved;
  return buildSocialMediaGuruProtectedSuccess({
    purpose: resolved.purpose,
    purposeKind: resolved.purposeKind,
    requestId: request.requestId,
    offeringId: request.offeringId ?? SOCIAL_MEDIA_GURU_OFFERING_ID,
  });
}

export function buildSocialMediaGuruProtectedSuccess(input: {
  purpose: string;
  purposeKind: SocialMediaGuruSupportedPurposeKind;
  requestId: string | null;
  offeringId: string | null;
  observedAt?: number;
}): SocialMediaGuruProtectedSuccessResult {
  const observedAt = input.observedAt ?? 1_720_000_000_000;
  const evidence = [
    {
      label: "synthetic_provenance",
      text: SOCIAL_MEDIA_GURU_LIMITATION,
      observedAt,
    },
    {
      label: "audience_behavior",
      text: SOCIAL_MEDIA_GURU_DATASET.audienceBehavior.join(" "),
      observedAt,
    },
    {
      label: "content_recommendations",
      text: SOCIAL_MEDIA_GURU_DATASET.contentRecommendations.join(" "),
      observedAt,
    },
  ];
  const content = [
    "Social Media Guru — controlled Testnet result",
    "",
    SOCIAL_MEDIA_GURU_LIMITATION,
    "",
    `Purpose: ${input.purpose}`,
    "",
    "Audience behavior:",
    ...SOCIAL_MEDIA_GURU_DATASET.audienceBehavior.map((line) => `- ${line}`),
    "",
    "Trending formats:",
    ...SOCIAL_MEDIA_GURU_DATASET.trendingFormats.map((line) => `- ${line}`),
    "",
    "Engagement tendencies:",
    ...SOCIAL_MEDIA_GURU_DATASET.engagementTendencies.map((line) => `- ${line}`),
    "",
    "Messaging themes:",
    ...SOCIAL_MEDIA_GURU_DATASET.messagingThemes.map((line) => `- ${line}`),
    "",
    "Channel differences:",
    ...SOCIAL_MEDIA_GURU_DATASET.channelDifferences.map((line) => `- ${line}`),
    "",
    "Demographic-style aggregates (synthetic):",
    ...SOCIAL_MEDIA_GURU_DATASET.demographicStyleAggregates.map(
      (line) => `- ${line}`,
    ),
    "",
    "Content recommendations:",
    ...SOCIAL_MEDIA_GURU_DATASET.contentRecommendations.map((line) => `- ${line}`),
    "",
    "Provenance: synthetic_test_provider. NOT live TikTok/Instagram/Facebook/X data.",
  ].join("\n");

  return {
    ok: true,
    productId: SOCIAL_MEDIA_GURU_PRODUCT_ID,
    resourceClass: SOCIAL_MEDIA_GURU_RESOURCE_CLASS,
    provenance: SOCIAL_MEDIA_GURU_PROVENANCE,
    limitation: SOCIAL_MEDIA_GURU_LIMITATION,
    purposeKind: input.purposeKind,
    purpose: input.purpose,
    requestId: input.requestId,
    offeringId: input.offeringId,
    serviceId: SOCIAL_MEDIA_GURU_SERVICE_ID,
    providerId: SOCIAL_MEDIA_GURU_PROVIDER_ID,
    evidence,
    payload: {
      platforms: [...SOCIAL_MEDIA_GURU_DATASET.platforms],
      audienceBehavior: [...SOCIAL_MEDIA_GURU_DATASET.audienceBehavior],
      trendingFormats: [...SOCIAL_MEDIA_GURU_DATASET.trendingFormats],
      engagementTendencies: [...SOCIAL_MEDIA_GURU_DATASET.engagementTendencies],
      messagingThemes: [...SOCIAL_MEDIA_GURU_DATASET.messagingThemes],
      channelDifferences: [...SOCIAL_MEDIA_GURU_DATASET.channelDifferences],
      demographicStyleAggregates: [
        ...SOCIAL_MEDIA_GURU_DATASET.demographicStyleAggregates,
      ],
      contentRecommendations: [
        ...SOCIAL_MEDIA_GURU_DATASET.contentRecommendations,
      ],
    },
    content,
  };
}

const PROTECTED_SUCCESS_KEYS = [
  "ok",
  "productId",
  "resourceClass",
  "provenance",
  "limitation",
  "purposeKind",
  "purpose",
  "requestId",
  "offeringId",
  "serviceId",
  "providerId",
  "evidence",
  "payload",
  "content",
] as const;
const MAX_ID_LENGTH = 256;
const MAX_CONTENT_LENGTH = 20_000;
const MAX_ITEM_TEXT_LENGTH = 2_000;
const MAX_ITEMS = 32;

function boundedString(value: unknown, max: number): value is string {
  return typeof value === "string" && value.length <= max && value.trim().length > 0;
}
function boundedStringArray(value: unknown, min: number): value is string[] {
  return (
    Array.isArray(value) &&
    value.length >= min &&
    value.length <= MAX_ITEMS &&
    value.every((item) => boundedString(item, MAX_ITEM_TEXT_LENGTH))
  );
}
function isPlainRecord(value: unknown): value is Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return false;
  const proto = Object.getPrototypeOf(value);
  return proto === Object.prototype || proto === null;
}

export function parseSocialMediaGuruProtectedSuccess(
  value: unknown,
): SocialMediaGuruProtectedSuccessResult | null {
  if (!isPlainRecord(value)) return null;
  const keys = Object.keys(value);
  if (keys.length !== PROTECTED_SUCCESS_KEYS.length) return null;
  if (!keys.every((key) => (PROTECTED_SUCCESS_KEYS as readonly string[]).includes(key)))
    return null;
  const r = value;
  if (r.ok !== true) return null;
  if (r.productId !== SOCIAL_MEDIA_GURU_PRODUCT_ID) return null;
  if (r.resourceClass !== SOCIAL_MEDIA_GURU_RESOURCE_CLASS) return null;
  if (r.provenance !== SOCIAL_MEDIA_GURU_PROVENANCE) return null;
  if (r.limitation !== SOCIAL_MEDIA_GURU_LIMITATION) return null;
  if (r.purposeKind !== SOCIAL_MEDIA_GURU_SUPPORTED_PURPOSE_KIND) return null;
  if (r.serviceId !== SOCIAL_MEDIA_GURU_SERVICE_ID) return null;
  if (r.providerId !== SOCIAL_MEDIA_GURU_PROVIDER_ID) return null;
  if (!boundedString(r.purpose, SOCIAL_MEDIA_GURU_PURPOSE_MAX_LENGTH)) return null;
  if (r.requestId !== null && !boundedString(r.requestId, MAX_ID_LENGTH)) return null;
  if (r.offeringId !== null && !boundedString(r.offeringId, MAX_ID_LENGTH)) return null;
  if (!boundedString(r.content, MAX_CONTENT_LENGTH)) return null;
  if (!Array.isArray(r.evidence) || r.evidence.length === 0 || r.evidence.length > MAX_ITEMS)
    return null;
  const evidence: SocialMediaGuruProtectedSuccessResult["evidence"] = [];
  for (const item of r.evidence) {
    if (!isPlainRecord(item) || Object.keys(item).length !== 3) return null;
    if (!boundedString(item.label, MAX_ID_LENGTH) || !boundedString(item.text, MAX_ITEM_TEXT_LENGTH))
      return null;
    if (typeof item.observedAt !== "number" || !Number.isFinite(item.observedAt)) return null;
    evidence.push({
      label: item.label,
      text: item.text,
      observedAt: item.observedAt,
    });
  }
  const payload = r.payload;
  if (!isPlainRecord(payload) || Object.keys(payload).length !== 8) return null;
  if (!boundedStringArray(payload.platforms, 1)) return null;
  if (!boundedStringArray(payload.audienceBehavior, 1)) return null;
  if (!boundedStringArray(payload.trendingFormats, 1)) return null;
  if (!boundedStringArray(payload.engagementTendencies, 1)) return null;
  if (!boundedStringArray(payload.messagingThemes, 1)) return null;
  if (!boundedStringArray(payload.channelDifferences, 1)) return null;
  if (!boundedStringArray(payload.demographicStyleAggregates, 1)) return null;
  if (!boundedStringArray(payload.contentRecommendations, 1)) return null;
  return {
    ok: true,
    productId: SOCIAL_MEDIA_GURU_PRODUCT_ID,
    resourceClass: SOCIAL_MEDIA_GURU_RESOURCE_CLASS,
    provenance: SOCIAL_MEDIA_GURU_PROVENANCE,
    limitation: SOCIAL_MEDIA_GURU_LIMITATION,
    purposeKind: SOCIAL_MEDIA_GURU_SUPPORTED_PURPOSE_KIND,
    purpose: r.purpose,
    requestId: r.requestId as string | null,
    offeringId: r.offeringId as string | null,
    serviceId: SOCIAL_MEDIA_GURU_SERVICE_ID,
    providerId: SOCIAL_MEDIA_GURU_PROVIDER_ID,
    evidence,
    payload: {
      platforms: [...payload.platforms],
      audienceBehavior: [...payload.audienceBehavior],
      trendingFormats: [...payload.trendingFormats],
      engagementTendencies: [...payload.engagementTendencies],
      messagingThemes: [...payload.messagingThemes],
      channelDifferences: [...payload.channelDifferences],
      demographicStyleAggregates: [...payload.demographicStyleAggregates],
      contentRecommendations: [...payload.contentRecommendations],
    },
    content: r.content,
  };
}

export function verifySocialMediaGuruProtectedResult(
  value: unknown,
): value is SocialMediaGuruProtectedSuccessResult {
  return parseSocialMediaGuruProtectedSuccess(value) !== null;
}

export type SocialMediaGuruAuthorizedRequest = {
  requestId: string;
  providerId: string;
  serviceId: string;
  offeringId: string;
  resourceClass: string;
  purposeKind: SocialMediaGuruSupportedPurposeKind;
  purpose: string;
};

export function socialMediaGuruAuthorizedRequestFromIntent(
  intent: ExecutionIntent,
):
  | { ok: true; request: SocialMediaGuruAuthorizedRequest }
  | { ok: false; reason: string } {
  const problems: string[] = [];
  const text = (value: unknown): string =>
    typeof value === "string" ? value.trim() : "";
  if (intent.kind !== "external_acquisition") {
    problems.push(`intent kind ${String(intent.kind)} is not an external acquisition`);
  }
  const requestId = text(intent.intentId);
  if (!requestId) problems.push("intent has no identity");
  const target: Partial<ExecutionIntent["target"]> = intent.target ?? {};
  const providerId = text(target.providerId);
  const serviceId = text(target.serviceId);
  const offeringId = text(target.offeringId);
  const resourceClass = text(target.resourceClass);
  if (!providerId) problems.push("authorized target has no providerId");
  else if (providerId !== SOCIAL_MEDIA_GURU_PROVIDER_ID) {
    problems.push(
      `authorized provider ${providerId} is not ${SOCIAL_MEDIA_GURU_PROVIDER_ID}`,
    );
  }
  if (!serviceId) problems.push("authorized target has no serviceId");
  else if (serviceId !== SOCIAL_MEDIA_GURU_FULFILLMENT_SCOPE.serviceId) {
    problems.push(
      `authorized service ${serviceId} is not ${SOCIAL_MEDIA_GURU_FULFILLMENT_SCOPE.serviceId}`,
    );
  }
  if (!offeringId) problems.push("authorized target has no offeringId");
  else if (offeringId !== SOCIAL_MEDIA_GURU_OFFERING_ID) {
    problems.push(
      `authorized offering ${offeringId} is not ${SOCIAL_MEDIA_GURU_OFFERING_ID}`,
    );
  }
  if (!resourceClass) problems.push("authorized target has no resourceClass");
  else if (
    !(SOCIAL_MEDIA_GURU_FULFILLMENT_SCOPE.resourceClasses as readonly string[]).includes(
      resourceClass,
    )
  ) {
    problems.push(
      `authorized resource class ${resourceClass} is not declared by the adapter`,
    );
  }
  const purposeKind = text(intent.requestedPurposeKind);
  if (!purposeKind) {
    problems.push(
      "intent carries no application-validated requested scope (requestedPurposeKind)",
    );
  } else if (
    !(SOCIAL_MEDIA_GURU_FULFILLMENT_SCOPE.purposeKinds as readonly string[]).includes(
      purposeKind,
    )
  ) {
    problems.push(
      `requested scope ${purposeKind.slice(0, 120)} is not declared by the adapter`,
    );
  }
  const purpose = normalizeSocialMediaGuruPurpose(intent.purpose);
  if (!purpose) problems.push("intent carries no bounded purpose");
  else {
    const claim = affirmativelyClaimsOutOfScopePhrase(purpose.toLowerCase());
    if (claim) problems.push(`requested purpose affirmatively requires ${claim}`);
  }
  if (problems.length > 0) return { ok: false, reason: problems.join("; ") };
  return {
    ok: true,
    request: {
      requestId,
      providerId,
      serviceId,
      offeringId,
      resourceClass,
      purposeKind: SOCIAL_MEDIA_GURU_SUPPORTED_PURPOSE_KIND,
      purpose,
    },
  };
}

export function normalizeSocialMediaGuruResult(
  raw: unknown,
  ctx?: {
    offeringId?: string;
    serviceId?: string;
    idempotencyKey?: string;
  },
): ExternalResourceResult {
  if (!verifySocialMediaGuruProtectedResult(raw)) {
    throw new Error(
      "social_media_guru: invalid protected result — expected verified synthetic Testnet social-intelligence payload",
    );
  }
  const evidence: ExternalResourceEvidence[] = raw.evidence.map((item) => ({
    label: item.label,
    text: item.text,
    observedAt: item.observedAt,
  }));
  return {
    offeringId: ctx?.offeringId ?? raw.offeringId ?? SOCIAL_MEDIA_GURU_OFFERING_ID,
    resourceClass: SOCIAL_MEDIA_GURU_RESOURCE_CLASS,
    payload: {
      ...raw.payload,
      content: raw.content,
      limitation: raw.limitation,
      provenance: raw.provenance,
      purpose: raw.purpose,
      purposeKind: raw.purposeKind,
    },
    evidence,
    retrievedAt: Date.now(),
    provenance: {
      providerId: SOCIAL_MEDIA_GURU_PROVIDER_ID,
      serviceId: ctx?.serviceId ?? raw.serviceId,
      idempotencyKey: ctx?.idempotencyKey ?? raw.requestId ?? "",
    },
  };
}

export function buildSocialMediaGuruRequest(input: {
  offering: MarketOffering;
  need: ResourceNeed;
}): {
  method: "GET";
  path: string;
  query: Record<string, string>;
  headers: Record<string, string>;
} {
  const purposeKind = validatedRequestedPurposeKind(input.need);
  const purpose = normalizeSocialMediaGuruPurpose(input.need.purpose);
  const headers: Record<string, string> = {
    "x-somebody-resource-class": SOCIAL_MEDIA_GURU_RESOURCE_CLASS,
    "x-somebody-product-id": SOCIAL_MEDIA_GURU_PRODUCT_ID,
    "x-somebody-service-id": SOCIAL_MEDIA_GURU_SERVICE_ID,
    "x-somebody-offering-id": SOCIAL_MEDIA_GURU_OFFERING_ID,
  };
  if (purpose) headers["x-somebody-purpose"] = purpose;
  if (purposeKind) headers["x-somebody-purpose-kind"] = purposeKind;
  if (input.need.id) headers["x-somebody-request-id"] = input.need.id;
  return {
    method: "GET",
    path: "/m3/social-media-guru",
    query: {},
    headers,
  };
}
